import { type ThemeConfig, theme } from "antd";
import { fonts, type Mode, palettes, status } from "./tokens";

export function antdTheme(mode: Mode): ThemeConfig {
	const p = palettes[mode];
	return {
		algorithm: mode === "dark" ? theme.darkAlgorithm : theme.defaultAlgorithm,
		token: {
			colorPrimary: p.accent,
			colorInfo: p.accent,
			colorSuccess: status.ok,
			colorWarning: status.amber,
			colorError: status.error,
			colorBgBase: p.bg,
			colorBgContainer: p.bg,
			colorBgElevated: p.bg,
			colorBgLayout: p.bg,
			colorBorder: p.border,
			colorBorderSecondary: p.border,
			colorText: p.text,
			colorTextSecondary: p.text2,
			colorTextTertiary: p.text3,
			colorFillSecondary: p.fill,
			colorFillTertiary: p.hover,
			fontFamily: fonts.sans,
			fontFamilyCode: fonts.mono,
			fontSize: 13,
			fontSizeSM: 12,
			fontSizeLG: 14,
			borderRadius: 4,
			borderRadiusSM: 2,
			borderRadiusLG: 8,
			controlHeight: 30,
			controlHeightSM: 24,
			boxShadow: p.shadow,
			boxShadowSecondary: p.shadow,
			motionDurationMid: "0.15s",
		},
		components: {
			Table: {
				headerBg: p.bg,
				headerColor: p.text2,
				headerSplitColor: "transparent",
				rowHoverBg: p.hover,
				rowSelectedBg: p.selected,
				rowSelectedHoverBg: p.selected,
				cellPaddingBlockSM: 8,
				cellPaddingInlineSM: 12,
				borderColor: p.border,
				fontSize: 13,
			},
			Tabs: { horizontalItemPadding: "10px 2px", horizontalItemGutter: 24, titleFontSize: 13 },
			Drawer: { paddingLG: 0 },
			Menu: {
				itemBg: "transparent",
				itemSelectedBg: p.fill,
				itemSelectedColor: p.text,
				itemHoverBg: p.hover,
				itemBorderRadius: 6,
				itemHeight: 34,
			},
			Card: { paddingLG: 16 },
			Tag: { defaultBg: p.fill, defaultColor: p.text2 },
			Segmented: { itemSelectedBg: p.bg, trackBg: p.fill },
			Button: { fontWeight: 500 },
			Modal: { titleFontSize: 15 },
		},
	};
}
