// Package store is tfy's SQLite persistence. Queries are generated by
// sqlc into package db from queries/*.sql; this package opens the database,
// applies migrations, and runs transactions.
package store

import (
	"context"
	"database/sql"
	"embed"
	"errors"
	"fmt"
	"io/fs"
	"net/url"
	"os"
	"path/filepath"
	"time"
	"unicode/utf8"

	"github.com/pressly/goose/v3"
	_ "modernc.org/sqlite"

	"github.com/raulsh/tfy/internal/store/db"
)

//go:embed migrations/*.sql
var migrations embed.FS

// Store wraps the database handle and the generated queries.
type Store struct {
	DB *sql.DB
	Q  *db.Queries
}

// Open opens (creating if needed) the database at path and migrates it.
func Open(ctx context.Context, path string) (*Store, error) {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return nil, err
	}
	q := url.Values{}
	for _, p := range []string{"foreign_keys(1)", "journal_mode(WAL)", "busy_timeout(10000)", "synchronous(NORMAL)"} {
		q.Add("_pragma", p)
	}
	// Write transactions take the lock up front, so two writers wait on each
	// other instead of failing on lock upgrade.
	q.Set("_txlock", "immediate")
	// A fixed format keeps times parseable and sortable as text.
	q.Set("_time_format", "sqlite")
	dsn := "file:" + path + "?" + q.Encode()

	sqldb, err := sql.Open("sqlite", dsn)
	if err != nil {
		return nil, err
	}
	sqldb.SetMaxOpenConns(8)
	if err := sqldb.PingContext(ctx); err != nil {
		sqldb.Close()
		return nil, fmt.Errorf("open %s: %w", path, err)
	}
	if err := migrate(ctx, sqldb); err != nil {
		sqldb.Close()
		return nil, err
	}
	return &Store{DB: sqldb, Q: db.New(sqldb)}, nil
}

func migrate(ctx context.Context, sqldb *sql.DB) error {
	sub, err := fs.Sub(migrations, "migrations")
	if err != nil {
		return err
	}
	p, err := goose.NewProvider(goose.DialectSQLite3, sqldb, sub)
	if err != nil {
		return err
	}
	if _, err := p.Up(ctx); err != nil {
		return fmt.Errorf("migrate: %w", err)
	}
	return nil
}

// Close closes the database.
func (s *Store) Close() error { return s.DB.Close() }

// Tx runs fn in a transaction, committing if it returns nil.
func (s *Store) Tx(ctx context.Context, fn func(q *db.Queries) error) error {
	tx, err := s.DB.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	if err := fn(s.Q.WithTx(tx)); err != nil {
		_ = tx.Rollback()
		return err
	}
	return tx.Commit()
}

// IsNotFound reports whether err is a missing-row error.
func IsNotFound(err error) bool { return errors.Is(err, sql.ErrNoRows) }

// Now is the timestamp every write uses: UTC without a monotonic reading.
func Now() time.Time { return time.Now().UTC().Round(0) }

// NullString converts "" to NULL.
func NullString(s string) sql.NullString { return sql.NullString{String: s, Valid: s != ""} }

// NullTime converts the zero time to NULL.
func NullTime(t time.Time) sql.NullTime { return sql.NullTime{Time: t, Valid: !t.IsZero()} }

// NowNull is Now for nullable timestamp columns (started_at, ended_at, …).
func NowNull() sql.NullTime { return NullTime(Now()) }

// RewritePathPrefix replaces the directory old with dir at the start of every
// absolute path the database stores, after the data directory moved.
func (s *Store) RewritePathPrefix(ctx context.Context, old, dir string) error {
	columns := []struct{ table, column string }{
		{"repos", "clone_path"}, {"unit_repos", "checkout_path"}, {"units", "workspace_path"}, {"runs", "cwd"},
	}
	n := utf8.RuneCountInString(old)
	tx, err := s.DB.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()
	for _, c := range columns {
		stmt := fmt.Sprintf("UPDATE %[1]s SET %[2]s = ? || substr(%[2]s, ?) WHERE %[2]s = ? OR substr(%[2]s, 1, ?) = ?", c.table, c.column)
		if _, err := tx.ExecContext(ctx, stmt, dir, n+1, old, n+1, old+"/"); err != nil {
			return fmt.Errorf("rewrite %s.%s: %w", c.table, c.column, err)
		}
	}
	return tx.Commit()
}
