// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addActivity = `-- name: AddActivity :exec
INSERT INTO activity (unit_id, project_id, at, actor, kind, message, data)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
`

type AddActivityParams struct {
	UnitID    sql.NullString `json:"unit_id"`
	ProjectID sql.NullString `json:"project_id"`
	At        time.Time      `json:"at"`
	Actor     string         `json:"actor"`
	Kind      string         `json:"kind"`
	Message   string         `json:"message"`
	Data      string         `json:"data"`
}

func (q *Queries) AddActivity(ctx context.Context, arg AddActivityParams) error {
	_, err := q.db.ExecContext(ctx, addActivity,
		arg.UnitID,
		arg.ProjectID,
		arg.At,
		arg.Actor,
		arg.Kind,
		arg.Message,
		arg.Data,
	)
	return err
}

const dailyDone = `-- name: DailyDone :many
SELECT CAST(date(at) AS TEXT) AS day, COUNT(*) AS n FROM activity
WHERE kind = 'transition' AND data LIKE '%"to":"done"%' AND at >= ?1
GROUP BY date(at) ORDER BY day
`

type DailyDoneRow struct {
	Day string `json:"day"`
	N   int64  `json:"n"`
}

func (q *Queries) DailyDone(ctx context.Context, since time.Time) ([]DailyDoneRow, error) {
	rows, err := q.db.QueryContext(ctx, dailyDone, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyDoneRow{}
	for rows.Next() {
		var i DailyDoneRow
		if err := rows.Scan(&i.Day, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentActivity = `-- name: ListRecentActivity :many
SELECT id, unit_id, project_id, at, actor, kind, message, data FROM activity ORDER BY id DESC LIMIT ?1
`

func (q *Queries) ListRecentActivity(ctx context.Context, lim int64) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, listRecentActivity, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.ProjectID,
			&i.At,
			&i.Actor,
			&i.Kind,
			&i.Message,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitActivity = `-- name: ListUnitActivity :many
SELECT id, unit_id, project_id, at, actor, kind, message, data FROM activity WHERE unit_id = ?1 ORDER BY id DESC LIMIT ?2
`

type ListUnitActivityParams struct {
	UnitID sql.NullString `json:"unit_id"`
	Lim    int64          `json:"lim"`
}

func (q *Queries) ListUnitActivity(ctx context.Context, arg ListUnitActivityParams) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, listUnitActivity, arg.UnitID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.ProjectID,
			&i.At,
			&i.Actor,
			&i.Kind,
			&i.Message,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
