// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifacts.sql

package db

import (
	"context"
	"time"
)

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (id, unit_id, path, version, content, content_type, size, sha256, removed, author, run_id, created_at)
VALUES (?1, ?2, ?3,
        (SELECT CAST(COALESCE(MAX(a.version), 0) + 1 AS INTEGER) FROM artifacts a WHERE a.unit_id = ?2 AND a.path = ?3),
        ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11)
RETURNING id, unit_id, path, version, content_type, size, sha256, removed, author, run_id, created_at
`

type CreateArtifactParams struct {
	ID          string    `json:"id"`
	UnitID      string    `json:"unit_id"`
	Path        string    `json:"path"`
	Content     []byte    `json:"content"`
	ContentType string    `json:"content_type"`
	Size        int64     `json:"size"`
	Sha256      string    `json:"sha256"`
	Removed     bool      `json:"removed"`
	Author      string    `json:"author"`
	RunID       string    `json:"run_id"`
	Now         time.Time `json:"now"`
}

type CreateArtifactRow struct {
	ID          string    `json:"id"`
	UnitID      string    `json:"unit_id"`
	Path        string    `json:"path"`
	Version     int64     `json:"version"`
	ContentType string    `json:"content_type"`
	Size        int64     `json:"size"`
	Sha256      string    `json:"sha256"`
	Removed     bool      `json:"removed"`
	Author      string    `json:"author"`
	RunID       string    `json:"run_id"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (CreateArtifactRow, error) {
	row := q.db.QueryRowContext(ctx, createArtifact,
		arg.ID,
		arg.UnitID,
		arg.Path,
		arg.Content,
		arg.ContentType,
		arg.Size,
		arg.Sha256,
		arg.Removed,
		arg.Author,
		arg.RunID,
		arg.Now,
	)
	var i CreateArtifactRow
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.Path,
		&i.Version,
		&i.ContentType,
		&i.Size,
		&i.Sha256,
		&i.Removed,
		&i.Author,
		&i.RunID,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifactVersion = `-- name: GetArtifactVersion :one
SELECT id, unit_id, path, version, content, content_type, size, sha256, removed, author, run_id, created_at FROM artifacts WHERE unit_id = ?1 AND path = ?2 AND version = ?3
`

type GetArtifactVersionParams struct {
	UnitID  string `json:"unit_id"`
	Path    string `json:"path"`
	Version int64  `json:"version"`
}

func (q *Queries) GetArtifactVersion(ctx context.Context, arg GetArtifactVersionParams) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifactVersion, arg.UnitID, arg.Path, arg.Version)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.Path,
		&i.Version,
		&i.Content,
		&i.ContentType,
		&i.Size,
		&i.Sha256,
		&i.Removed,
		&i.Author,
		&i.RunID,
		&i.CreatedAt,
	)
	return i, err
}

const latestArtifacts = `-- name: LatestArtifacts :many
SELECT a.id, a.unit_id, a.path, a.version, a.content_type, a.size, a.sha256, a.removed, a.author, a.run_id, a.created_at
FROM artifacts a
WHERE a.unit_id = ?1
  AND a.version = (SELECT MAX(b.version) FROM artifacts b WHERE b.unit_id = a.unit_id AND b.path = a.path)
ORDER BY a.path
`

type LatestArtifactsRow struct {
	ID          string    `json:"id"`
	UnitID      string    `json:"unit_id"`
	Path        string    `json:"path"`
	Version     int64     `json:"version"`
	ContentType string    `json:"content_type"`
	Size        int64     `json:"size"`
	Sha256      string    `json:"sha256"`
	Removed     bool      `json:"removed"`
	Author      string    `json:"author"`
	RunID       string    `json:"run_id"`
	CreatedAt   time.Time `json:"created_at"`
}

// The latest version of each of a unit's artifacts, removed ones included.
func (q *Queries) LatestArtifacts(ctx context.Context, unitID string) ([]LatestArtifactsRow, error) {
	rows, err := q.db.QueryContext(ctx, latestArtifacts, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestArtifactsRow{}
	for rows.Next() {
		var i LatestArtifactsRow
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.Path,
			&i.Version,
			&i.ContentType,
			&i.Size,
			&i.Sha256,
			&i.Removed,
			&i.Author,
			&i.RunID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactVersions = `-- name: ListArtifactVersions :many
SELECT id, unit_id, path, version, content_type, size, sha256, removed, author, run_id, created_at FROM artifacts
WHERE unit_id = ?1 AND path = ?2 ORDER BY version DESC
`

type ListArtifactVersionsParams struct {
	UnitID string `json:"unit_id"`
	Path   string `json:"path"`
}

type ListArtifactVersionsRow struct {
	ID          string    `json:"id"`
	UnitID      string    `json:"unit_id"`
	Path        string    `json:"path"`
	Version     int64     `json:"version"`
	ContentType string    `json:"content_type"`
	Size        int64     `json:"size"`
	Sha256      string    `json:"sha256"`
	Removed     bool      `json:"removed"`
	Author      string    `json:"author"`
	RunID       string    `json:"run_id"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) ListArtifactVersions(ctx context.Context, arg ListArtifactVersionsParams) ([]ListArtifactVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactVersions, arg.UnitID, arg.Path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtifactVersionsRow{}
	for rows.Next() {
		var i ListArtifactVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.Path,
			&i.Version,
			&i.ContentType,
			&i.Size,
			&i.Sha256,
			&i.Removed,
			&i.Author,
			&i.RunID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
