// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package db

import (
	"context"
	"time"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (id, unit_id, kind, version, content, meta, author, run_id, created_at)
VALUES (?1, ?2, ?3,
        (SELECT CAST(COALESCE(MAX(d.version), 0) + 1 AS INTEGER) FROM documents d WHERE d.unit_id = ?2 AND d.kind = ?3),
        ?4, ?5, ?6, ?7, ?8)
RETURNING id, unit_id, kind, version, content, meta, author, run_id, created_at
`

type CreateDocumentParams struct {
	ID      string    `json:"id"`
	UnitID  string    `json:"unit_id"`
	Kind    string    `json:"kind"`
	Content string    `json:"content"`
	Meta    string    `json:"meta"`
	Author  string    `json:"author"`
	RunID   string    `json:"run_id"`
	Now     time.Time `json:"now"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.ID,
		arg.UnitID,
		arg.Kind,
		arg.Content,
		arg.Meta,
		arg.Author,
		arg.RunID,
		arg.Now,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.Kind,
		&i.Version,
		&i.Content,
		&i.Meta,
		&i.Author,
		&i.RunID,
		&i.CreatedAt,
	)
	return i, err
}

const getDocumentVersion = `-- name: GetDocumentVersion :one
SELECT id, unit_id, kind, version, content, meta, author, run_id, created_at FROM documents WHERE unit_id = ?1 AND kind = ?2 AND version = ?3
`

type GetDocumentVersionParams struct {
	UnitID  string `json:"unit_id"`
	Kind    string `json:"kind"`
	Version int64  `json:"version"`
}

func (q *Queries) GetDocumentVersion(ctx context.Context, arg GetDocumentVersionParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentVersion, arg.UnitID, arg.Kind, arg.Version)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.Kind,
		&i.Version,
		&i.Content,
		&i.Meta,
		&i.Author,
		&i.RunID,
		&i.CreatedAt,
	)
	return i, err
}

const latestDocument = `-- name: LatestDocument :one
SELECT id, unit_id, kind, version, content, meta, author, run_id, created_at FROM documents WHERE unit_id = ?1 AND kind = ?2 ORDER BY version DESC LIMIT 1
`

type LatestDocumentParams struct {
	UnitID string `json:"unit_id"`
	Kind   string `json:"kind"`
}

func (q *Queries) LatestDocument(ctx context.Context, arg LatestDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, latestDocument, arg.UnitID, arg.Kind)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.Kind,
		&i.Version,
		&i.Content,
		&i.Meta,
		&i.Author,
		&i.RunID,
		&i.CreatedAt,
	)
	return i, err
}

const listDocumentVersions = `-- name: ListDocumentVersions :many
SELECT id, kind, version, author, run_id, created_at FROM documents
WHERE unit_id = ?1 AND kind = ?2 ORDER BY version DESC
`

type ListDocumentVersionsParams struct {
	UnitID string `json:"unit_id"`
	Kind   string `json:"kind"`
}

type ListDocumentVersionsRow struct {
	ID        string    `json:"id"`
	Kind      string    `json:"kind"`
	Version   int64     `json:"version"`
	Author    string    `json:"author"`
	RunID     string    `json:"run_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListDocumentVersions(ctx context.Context, arg ListDocumentVersionsParams) ([]ListDocumentVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentVersions, arg.UnitID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentVersionsRow{}
	for rows.Next() {
		var i ListDocumentVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Version,
			&i.Author,
			&i.RunID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
