// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issues.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const deleteUnitIssue = `-- name: DeleteUnitIssue :exec
DELETE FROM unit_issues WHERE id = ?1 AND unit_id = ?2
`

type DeleteUnitIssueParams struct {
	ID     string `json:"id"`
	UnitID string `json:"unit_id"`
}

func (q *Queries) DeleteUnitIssue(ctx context.Context, arg DeleteUnitIssueParams) error {
	_, err := q.db.ExecContext(ctx, deleteUnitIssue, arg.ID, arg.UnitID)
	return err
}

const getUnitIssue = `-- name: GetUnitIssue :one
SELECT id, unit_id, repo, number, url, title, state, author, labels, body, comments, public, closes, issue_updated_at, fetched_at, suggestion, suggestion_state, created_at, updated_at FROM unit_issues WHERE id = ?1 AND unit_id = ?2
`

type GetUnitIssueParams struct {
	ID     string `json:"id"`
	UnitID string `json:"unit_id"`
}

func (q *Queries) GetUnitIssue(ctx context.Context, arg GetUnitIssueParams) (UnitIssue, error) {
	row := q.db.QueryRowContext(ctx, getUnitIssue, arg.ID, arg.UnitID)
	var i UnitIssue
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.Repo,
		&i.Number,
		&i.Url,
		&i.Title,
		&i.State,
		&i.Author,
		&i.Labels,
		&i.Body,
		&i.Comments,
		&i.Public,
		&i.Closes,
		&i.IssueUpdatedAt,
		&i.FetchedAt,
		&i.Suggestion,
		&i.SuggestionState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkUnitIssue = `-- name: LinkUnitIssue :one
INSERT INTO unit_issues (id, unit_id, repo, number, closes, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?6)
ON CONFLICT (unit_id, repo, number) DO UPDATE SET closes = excluded.closes, updated_at = excluded.updated_at
RETURNING id, unit_id, repo, number, url, title, state, author, labels, body, comments, public, closes, issue_updated_at, fetched_at, suggestion, suggestion_state, created_at, updated_at
`

type LinkUnitIssueParams struct {
	ID     string    `json:"id"`
	UnitID string    `json:"unit_id"`
	Repo   string    `json:"repo"`
	Number int64     `json:"number"`
	Closes bool      `json:"closes"`
	Now    time.Time `json:"now"`
}

func (q *Queries) LinkUnitIssue(ctx context.Context, arg LinkUnitIssueParams) (UnitIssue, error) {
	row := q.db.QueryRowContext(ctx, linkUnitIssue,
		arg.ID,
		arg.UnitID,
		arg.Repo,
		arg.Number,
		arg.Closes,
		arg.Now,
	)
	var i UnitIssue
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.Repo,
		&i.Number,
		&i.Url,
		&i.Title,
		&i.State,
		&i.Author,
		&i.Labels,
		&i.Body,
		&i.Comments,
		&i.Public,
		&i.Closes,
		&i.IssueUpdatedAt,
		&i.FetchedAt,
		&i.Suggestion,
		&i.SuggestionState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIssueUnits = `-- name: ListIssueUnits :many
SELECT ui.repo, ui.number, u.id AS unit_id, u.seq, u.state FROM unit_issues ui
JOIN units u ON u.id = ui.unit_id
WHERE u.project_id = ?1
`

type ListIssueUnitsRow struct {
	Repo   string `json:"repo"`
	Number int64  `json:"number"`
	UnitID string `json:"unit_id"`
	Seq    int64  `json:"seq"`
	State  string `json:"state"`
}

// The units an issue is linked to, for the picker.
func (q *Queries) ListIssueUnits(ctx context.Context, projectID string) ([]ListIssueUnitsRow, error) {
	rows, err := q.db.QueryContext(ctx, listIssueUnits, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssueUnitsRow{}
	for rows.Next() {
		var i ListIssueUnitsRow
		if err := rows.Scan(
			&i.Repo,
			&i.Number,
			&i.UnitID,
			&i.Seq,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitIssues = `-- name: ListUnitIssues :many
SELECT id, unit_id, repo, number, url, title, state, author, labels, body, comments, public, closes, issue_updated_at, fetched_at, suggestion, suggestion_state, created_at, updated_at FROM unit_issues WHERE unit_id = ?1 ORDER BY created_at, number
`

func (q *Queries) ListUnitIssues(ctx context.Context, unitID string) ([]UnitIssue, error) {
	rows, err := q.db.QueryContext(ctx, listUnitIssues, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnitIssue{}
	for rows.Next() {
		var i UnitIssue
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.Repo,
			&i.Number,
			&i.Url,
			&i.Title,
			&i.State,
			&i.Author,
			&i.Labels,
			&i.Body,
			&i.Comments,
			&i.Public,
			&i.Closes,
			&i.IssueUpdatedAt,
			&i.FetchedAt,
			&i.Suggestion,
			&i.SuggestionState,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUnitIssueCloses = `-- name: SetUnitIssueCloses :exec
UPDATE unit_issues SET closes = ?1, updated_at = ?2 WHERE id = ?3
`

type SetUnitIssueClosesParams struct {
	Closes bool      `json:"closes"`
	Now    time.Time `json:"now"`
	ID     string    `json:"id"`
}

func (q *Queries) SetUnitIssueCloses(ctx context.Context, arg SetUnitIssueClosesParams) error {
	_, err := q.db.ExecContext(ctx, setUnitIssueCloses, arg.Closes, arg.Now, arg.ID)
	return err
}

const setUnitIssueSuggestion = `-- name: SetUnitIssueSuggestion :exec
UPDATE unit_issues SET suggestion = ?1, suggestion_state = ?2, updated_at = ?3 WHERE id = ?4
`

type SetUnitIssueSuggestionParams struct {
	Suggestion      string    `json:"suggestion"`
	SuggestionState string    `json:"suggestion_state"`
	Now             time.Time `json:"now"`
	ID              string    `json:"id"`
}

func (q *Queries) SetUnitIssueSuggestion(ctx context.Context, arg SetUnitIssueSuggestionParams) error {
	_, err := q.db.ExecContext(ctx, setUnitIssueSuggestion,
		arg.Suggestion,
		arg.SuggestionState,
		arg.Now,
		arg.ID,
	)
	return err
}

const updateUnitIssueContent = `-- name: UpdateUnitIssueContent :exec
UPDATE unit_issues
SET url = ?1, title = ?2, state = ?3, author = ?4, labels = ?5, body = ?6,
    comments = ?7, public = ?8, issue_updated_at = ?9, fetched_at = ?10, updated_at = ?10
WHERE id = ?11
`

type UpdateUnitIssueContentParams struct {
	Url            string       `json:"url"`
	Title          string       `json:"title"`
	State          string       `json:"state"`
	Author         string       `json:"author"`
	Labels         string       `json:"labels"`
	Body           string       `json:"body"`
	Comments       string       `json:"comments"`
	Public         bool         `json:"public"`
	IssueUpdatedAt sql.NullTime `json:"issue_updated_at"`
	Now            sql.NullTime `json:"now"`
	ID             string       `json:"id"`
}

func (q *Queries) UpdateUnitIssueContent(ctx context.Context, arg UpdateUnitIssueContentParams) error {
	_, err := q.db.ExecContext(ctx, updateUnitIssueContent,
		arg.Url,
		arg.Title,
		arg.State,
		arg.Author,
		arg.Labels,
		arg.Body,
		arg.Comments,
		arg.Public,
		arg.IssueUpdatedAt,
		arg.Now,
		arg.ID,
	)
	return err
}
