// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const activeJobForUnit = `-- name: ActiveJobForUnit :one
SELECT id, kind, unit_id, project_id, payload, status, attempts, dedupe_key, run_after, error, created_at, started_at, finished_at FROM jobs WHERE unit_id = ?1 AND status IN ('queued', 'running') ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) ActiveJobForUnit(ctx context.Context, unitID sql.NullString) (Job, error) {
	row := q.db.QueryRowContext(ctx, activeJobForUnit, unitID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.UnitID,
		&i.ProjectID,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.DedupeKey,
		&i.RunAfter,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const cancelQueuedJobsForUnit = `-- name: CancelQueuedJobsForUnit :exec
UPDATE jobs SET status = 'cancelled', finished_at = ?1 WHERE unit_id = ?2 AND status = 'queued'
`

type CancelQueuedJobsForUnitParams struct {
	Now    sql.NullTime   `json:"now"`
	UnitID sql.NullString `json:"unit_id"`
}

func (q *Queries) CancelQueuedJobsForUnit(ctx context.Context, arg CancelQueuedJobsForUnitParams) error {
	_, err := q.db.ExecContext(ctx, cancelQueuedJobsForUnit, arg.Now, arg.UnitID)
	return err
}

const claimJob = `-- name: ClaimJob :one
UPDATE jobs SET status = 'running', attempts = attempts + 1, started_at = ?1
WHERE id = (SELECT j.id FROM jobs j
            WHERE j.status = 'queued' AND j.run_after <= ?1 AND j.kind IN (/*SLICE:kinds*/?)
            ORDER BY j.run_after, j.created_at LIMIT 1)
RETURNING id, kind, unit_id, project_id, payload, status, attempts, dedupe_key, run_after, error, created_at, started_at, finished_at
`

type ClaimJobParams struct {
	Now   sql.NullTime `json:"now"`
	Kinds []string     `json:"kinds"`
}

func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (Job, error) {
	query := claimJob
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Now)
	if len(arg.Kinds) > 0 {
		for _, v := range arg.Kinds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:kinds*/?", strings.Repeat(",?", len(arg.Kinds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:kinds*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.UnitID,
		&i.ProjectID,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.DedupeKey,
		&i.RunAfter,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO jobs (id, kind, unit_id, project_id, payload, status, dedupe_key, run_after, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, 'queued', ?6, ?7, ?8)
RETURNING id, kind, unit_id, project_id, payload, status, attempts, dedupe_key, run_after, error, created_at, started_at, finished_at
`

type EnqueueJobParams struct {
	ID        string         `json:"id"`
	Kind      string         `json:"kind"`
	UnitID    sql.NullString `json:"unit_id"`
	ProjectID sql.NullString `json:"project_id"`
	Payload   string         `json:"payload"`
	DedupeKey sql.NullString `json:"dedupe_key"`
	RunAfter  time.Time      `json:"run_after"`
	Now       time.Time      `json:"now"`
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, enqueueJob,
		arg.ID,
		arg.Kind,
		arg.UnitID,
		arg.ProjectID,
		arg.Payload,
		arg.DedupeKey,
		arg.RunAfter,
		arg.Now,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.UnitID,
		&i.ProjectID,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.DedupeKey,
		&i.RunAfter,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishJob = `-- name: FinishJob :exec
UPDATE jobs SET status = ?1, error = ?2, finished_at = ?3 WHERE id = ?4
`

type FinishJobParams struct {
	Status string       `json:"status"`
	Error  string       `json:"error"`
	Now    sql.NullTime `json:"now"`
	ID     string       `json:"id"`
}

func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) error {
	_, err := q.db.ExecContext(ctx, finishJob,
		arg.Status,
		arg.Error,
		arg.Now,
		arg.ID,
	)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, kind, unit_id, project_id, payload, status, attempts, dedupe_key, run_after, error, created_at, started_at, finished_at FROM jobs WHERE id = ?1
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.UnitID,
		&i.ProjectID,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.DedupeKey,
		&i.RunAfter,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listBusyUnitIDs = `-- name: ListBusyUnitIDs :many
SELECT DISTINCT CAST(unit_id AS TEXT) AS unit_id FROM jobs WHERE status IN ('queued', 'running') AND unit_id IS NOT NULL
`

func (q *Queries) ListBusyUnitIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listBusyUnitIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var unit_id string
		if err := rows.Scan(&unit_id); err != nil {
			return nil, err
		}
		items = append(items, unit_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningJobs = `-- name: ListRunningJobs :many
SELECT id, kind, unit_id, project_id, payload, status, attempts, dedupe_key, run_after, error, created_at, started_at, finished_at FROM jobs WHERE status = 'running'
`

func (q *Queries) ListRunningJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listRunningJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.UnitID,
			&i.ProjectID,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.DedupeKey,
			&i.RunAfter,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseJobDedupe = `-- name: ReleaseJobDedupe :exec
UPDATE jobs SET dedupe_key = NULL WHERE id = ?1
`

// A running job hands its dedupe key over to the successor it enqueues.
func (q *Queries) ReleaseJobDedupe(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, releaseJobDedupe, id)
	return err
}

const requeueJob = `-- name: RequeueJob :exec
UPDATE jobs SET status = 'queued', run_after = ?1, error = ?2 WHERE id = ?3
`

type RequeueJobParams struct {
	RunAfter time.Time `json:"run_after"`
	Error    string    `json:"error"`
	ID       string    `json:"id"`
}

func (q *Queries) RequeueJob(ctx context.Context, arg RequeueJobParams) error {
	_, err := q.db.ExecContext(ctx, requeueJob, arg.RunAfter, arg.Error, arg.ID)
	return err
}
