// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Activity struct {
	ID        int64          `json:"id"`
	UnitID    sql.NullString `json:"unit_id"`
	ProjectID sql.NullString `json:"project_id"`
	At        time.Time      `json:"at"`
	Actor     string         `json:"actor"`
	Kind      string         `json:"kind"`
	Message   string         `json:"message"`
	Data      string         `json:"data"`
}

type Document struct {
	ID        string    `json:"id"`
	UnitID    string    `json:"unit_id"`
	Kind      string    `json:"kind"`
	Version   int64     `json:"version"`
	Content   string    `json:"content"`
	Meta      string    `json:"meta"`
	Author    string    `json:"author"`
	RunID     string    `json:"run_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Feedback struct {
	ID           string         `json:"id"`
	ProjectID    string         `json:"project_id"`
	SourceID     sql.NullString `json:"source_id"`
	ChannelID    string         `json:"channel_id"`
	ChannelName  string         `json:"channel_name"`
	Ts           string         `json:"ts"`
	ThreadTs     string         `json:"thread_ts"`
	AuthorID     string         `json:"author_id"`
	AuthorName   string         `json:"author_name"`
	Text         string         `json:"text"`
	Permalink    string         `json:"permalink"`
	ReplyCount   int64          `json:"reply_count"`
	Edited       bool           `json:"edited"`
	PostedAt     time.Time      `json:"posted_at"`
	TriageStatus string         `json:"triage_status"`
	Triage       string         `json:"triage"`
	UnitID       sql.NullString `json:"unit_id"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type Job struct {
	ID         string         `json:"id"`
	Kind       string         `json:"kind"`
	UnitID     sql.NullString `json:"unit_id"`
	ProjectID  sql.NullString `json:"project_id"`
	Payload    string         `json:"payload"`
	Status     string         `json:"status"`
	Attempts   int64          `json:"attempts"`
	DedupeKey  sql.NullString `json:"dedupe_key"`
	RunAfter   time.Time      `json:"run_after"`
	Error      string         `json:"error"`
	CreatedAt  time.Time      `json:"created_at"`
	StartedAt  sql.NullTime   `json:"started_at"`
	FinishedAt sql.NullTime   `json:"finished_at"`
}

type Project struct {
	ID             string    `json:"id"`
	Name           string    `json:"name"`
	Slug           string    `json:"slug"`
	Description    string    `json:"description"`
	ProductContext string    `json:"product_context"`
	Settings       string    `json:"settings"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	Conventions    string    `json:"conventions"`
}

type Repo struct {
	ID            string    `json:"id"`
	ProjectID     string    `json:"project_id"`
	FullName      string    `json:"full_name"`
	DefaultBranch string    `json:"default_branch"`
	CloneUrl      string    `json:"clone_url"`
	ClonePath     string    `json:"clone_path"`
	CreatedAt     time.Time `json:"created_at"`
}

type Run struct {
	ID             string         `json:"id"`
	UnitID         sql.NullString `json:"unit_id"`
	ProjectID      sql.NullString `json:"project_id"`
	ParentRunID    string         `json:"parent_run_id"`
	Kind           string         `json:"kind"`
	Status         string         `json:"status"`
	Reason         string         `json:"reason"`
	SessionID      string         `json:"session_id"`
	Model          string         `json:"model"`
	Effort         string         `json:"effort"`
	PermissionMode string         `json:"permission_mode"`
	PromptVersion  string         `json:"prompt_version"`
	Cwd            string         `json:"cwd"`
	Pid            int64          `json:"pid"`
	CostUsd        float64        `json:"cost_usd"`
	CostTotalUsd   float64        `json:"cost_total_usd"`
	InputTokens    int64          `json:"input_tokens"`
	OutputTokens   int64          `json:"output_tokens"`
	Turns          int64          `json:"turns"`
	Denials        int64          `json:"denials"`
	Result         string         `json:"result"`
	CreatedAt      time.Time      `json:"created_at"`
	StartedAt      sql.NullTime   `json:"started_at"`
	EndedAt        sql.NullTime   `json:"ended_at"`
}

type RunEvent struct {
	RunID   string    `json:"run_id"`
	Seq     int64     `json:"seq"`
	At      time.Time `json:"at"`
	Type    string    `json:"type"`
	Subtype string    `json:"subtype"`
	Tool    string    `json:"tool"`
	Summary string    `json:"summary"`
	Payload string    `json:"payload"`
}

type SlackSource struct {
	ID                string       `json:"id"`
	ProjectID         string       `json:"project_id"`
	ChannelID         string       `json:"channel_id"`
	ChannelName       string       `json:"channel_name"`
	AutoTriage        bool         `json:"auto_triage"`
	ExcludeBots       bool         `json:"exclude_bots"`
	PollIntervalS     int64        `json:"poll_interval_s"`
	CursorTs          string       `json:"cursor_ts"`
	LastPolledAt      sql.NullTime `json:"last_polled_at"`
	LastThreadSweepAt sql.NullTime `json:"last_thread_sweep_at"`
	LastError         string       `json:"last_error"`
	CreatedAt         time.Time    `json:"created_at"`
}

type Unit struct {
	ID              string         `json:"id"`
	Seq             int64          `json:"seq"`
	ProjectID       string         `json:"project_id"`
	ParentUnitID    sql.NullString `json:"parent_unit_id"`
	Kind            string         `json:"kind"`
	Title           string         `json:"title"`
	Summary         string         `json:"summary"`
	Description     string         `json:"description"`
	Origin          string         `json:"origin"`
	State           string         `json:"state"`
	Attention       string         `json:"attention"`
	AttentionDetail string         `json:"attention_detail"`
	ReviewIteration int64          `json:"review_iteration"`
	WorkspacePath   string         `json:"workspace_path"`
	CreatedBy       string         `json:"created_by"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	MergeRound      int64          `json:"merge_round"`
	MergeAdmin      bool           `json:"merge_admin"`
}

type UnitIssue struct {
	ID              string       `json:"id"`
	UnitID          string       `json:"unit_id"`
	Repo            string       `json:"repo"`
	Number          int64        `json:"number"`
	Url             string       `json:"url"`
	Title           string       `json:"title"`
	State           string       `json:"state"`
	Author          string       `json:"author"`
	Labels          string       `json:"labels"`
	Body            string       `json:"body"`
	Comments        string       `json:"comments"`
	Public          bool         `json:"public"`
	Closes          bool         `json:"closes"`
	IssueUpdatedAt  sql.NullTime `json:"issue_updated_at"`
	FetchedAt       sql.NullTime `json:"fetched_at"`
	Suggestion      string       `json:"suggestion"`
	SuggestionState string       `json:"suggestion_state"`
	CreatedAt       time.Time    `json:"created_at"`
	UpdatedAt       time.Time    `json:"updated_at"`
}

type UnitRepo struct {
	UnitID       string       `json:"unit_id"`
	RepoID       string       `json:"repo_id"`
	CheckoutPath string       `json:"checkout_path"`
	BaseSha      string       `json:"base_sha"`
	IsTarget     bool         `json:"is_target"`
	Branch       string       `json:"branch"`
	HeadSha      string       `json:"head_sha"`
	ReviewedSha  string       `json:"reviewed_sha"`
	PublishState string       `json:"publish_state"`
	PrNumber     int64        `json:"pr_number"`
	PrUrl        string       `json:"pr_url"`
	PrState      string       `json:"pr_state"`
	ChecksState  string       `json:"checks_state"`
	MergeSha     string       `json:"merge_sha"`
	MergedAt     sql.NullTime `json:"merged_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	ReleaseState string       `json:"release_state"`
	ReleaseRuns  string       `json:"release_runs"`
}
