// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repos.sql

package db

import (
	"context"
	"time"
)

const createRepo = `-- name: CreateRepo :one
INSERT INTO repos (id, project_id, full_name, default_branch, clone_url, clone_path, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
RETURNING id, project_id, full_name, default_branch, clone_url, clone_path, created_at
`

type CreateRepoParams struct {
	ID            string    `json:"id"`
	ProjectID     string    `json:"project_id"`
	FullName      string    `json:"full_name"`
	DefaultBranch string    `json:"default_branch"`
	CloneUrl      string    `json:"clone_url"`
	ClonePath     string    `json:"clone_path"`
	Now           time.Time `json:"now"`
}

func (q *Queries) CreateRepo(ctx context.Context, arg CreateRepoParams) (Repo, error) {
	row := q.db.QueryRowContext(ctx, createRepo,
		arg.ID,
		arg.ProjectID,
		arg.FullName,
		arg.DefaultBranch,
		arg.CloneUrl,
		arg.ClonePath,
		arg.Now,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FullName,
		&i.DefaultBranch,
		&i.CloneUrl,
		&i.ClonePath,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRepo = `-- name: DeleteRepo :exec
DELETE FROM repos WHERE id = ?1 AND project_id = ?2
`

type DeleteRepoParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) DeleteRepo(ctx context.Context, arg DeleteRepoParams) error {
	_, err := q.db.ExecContext(ctx, deleteRepo, arg.ID, arg.ProjectID)
	return err
}

const getRepo = `-- name: GetRepo :one
SELECT id, project_id, full_name, default_branch, clone_url, clone_path, created_at FROM repos WHERE id = ?1
`

func (q *Queries) GetRepo(ctx context.Context, id string) (Repo, error) {
	row := q.db.QueryRowContext(ctx, getRepo, id)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FullName,
		&i.DefaultBranch,
		&i.CloneUrl,
		&i.ClonePath,
		&i.CreatedAt,
	)
	return i, err
}

const listAllRepos = `-- name: ListAllRepos :many
SELECT id, project_id, full_name, default_branch, clone_url, clone_path, created_at FROM repos ORDER BY full_name
`

func (q *Queries) ListAllRepos(ctx context.Context) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, listAllRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repo{}
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FullName,
			&i.DefaultBranch,
			&i.CloneUrl,
			&i.ClonePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposByProject = `-- name: ListReposByProject :many
SELECT id, project_id, full_name, default_branch, clone_url, clone_path, created_at FROM repos WHERE project_id = ?1 ORDER BY full_name
`

func (q *Queries) ListReposByProject(ctx context.Context, projectID string) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, listReposByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repo{}
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FullName,
			&i.DefaultBranch,
			&i.CloneUrl,
			&i.ClonePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRepoClone = `-- name: UpdateRepoClone :exec
UPDATE repos SET clone_url = ?1, clone_path = ?2, default_branch = ?3 WHERE id = ?4
`

type UpdateRepoCloneParams struct {
	CloneUrl      string `json:"clone_url"`
	ClonePath     string `json:"clone_path"`
	DefaultBranch string `json:"default_branch"`
	ID            string `json:"id"`
}

func (q *Queries) UpdateRepoClone(ctx context.Context, arg UpdateRepoCloneParams) error {
	_, err := q.db.ExecContext(ctx, updateRepoClone,
		arg.CloneUrl,
		arg.ClonePath,
		arg.DefaultBranch,
		arg.ID,
	)
	return err
}
