// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: run_events.sql

package db

import (
	"context"
	"time"
)

const insertRunEvent = `-- name: InsertRunEvent :exec
INSERT INTO run_events (run_id, seq, at, type, subtype, tool, summary, payload)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
`

type InsertRunEventParams struct {
	RunID   string    `json:"run_id"`
	Seq     int64     `json:"seq"`
	At      time.Time `json:"at"`
	Type    string    `json:"type"`
	Subtype string    `json:"subtype"`
	Tool    string    `json:"tool"`
	Summary string    `json:"summary"`
	Payload string    `json:"payload"`
}

func (q *Queries) InsertRunEvent(ctx context.Context, arg InsertRunEventParams) error {
	_, err := q.db.ExecContext(ctx, insertRunEvent,
		arg.RunID,
		arg.Seq,
		arg.At,
		arg.Type,
		arg.Subtype,
		arg.Tool,
		arg.Summary,
		arg.Payload,
	)
	return err
}

const listRunEvents = `-- name: ListRunEvents :many
SELECT run_id, seq, at, type, subtype, tool, summary, payload FROM run_events WHERE run_id = ?1 AND seq > ?2 ORDER BY seq LIMIT ?3
`

type ListRunEventsParams struct {
	RunID string `json:"run_id"`
	After int64  `json:"after"`
	Lim   int64  `json:"lim"`
}

func (q *Queries) ListRunEvents(ctx context.Context, arg ListRunEventsParams) ([]RunEvent, error) {
	rows, err := q.db.QueryContext(ctx, listRunEvents, arg.RunID, arg.After, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunEvent{}
	for rows.Next() {
		var i RunEvent
		if err := rows.Scan(
			&i.RunID,
			&i.Seq,
			&i.At,
			&i.Type,
			&i.Subtype,
			&i.Tool,
			&i.Summary,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
