// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createRun = `-- name: CreateRun :one
INSERT INTO runs (id, unit_id, project_id, parent_run_id, kind, status, model, effort, permission_mode, prompt_version, cwd, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, 'queued', ?6, ?7, ?8, ?9, ?10, ?11)
RETURNING id, unit_id, project_id, parent_run_id, kind, status, reason, session_id, model, effort, permission_mode, prompt_version, cwd, pid, cost_usd, cost_total_usd, input_tokens, output_tokens, turns, denials, result, created_at, started_at, ended_at
`

type CreateRunParams struct {
	ID             string         `json:"id"`
	UnitID         sql.NullString `json:"unit_id"`
	ProjectID      sql.NullString `json:"project_id"`
	ParentRunID    string         `json:"parent_run_id"`
	Kind           string         `json:"kind"`
	Model          string         `json:"model"`
	Effort         string         `json:"effort"`
	PermissionMode string         `json:"permission_mode"`
	PromptVersion  string         `json:"prompt_version"`
	Cwd            string         `json:"cwd"`
	Now            time.Time      `json:"now"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, createRun,
		arg.ID,
		arg.UnitID,
		arg.ProjectID,
		arg.ParentRunID,
		arg.Kind,
		arg.Model,
		arg.Effort,
		arg.PermissionMode,
		arg.PromptVersion,
		arg.Cwd,
		arg.Now,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.ProjectID,
		&i.ParentRunID,
		&i.Kind,
		&i.Status,
		&i.Reason,
		&i.SessionID,
		&i.Model,
		&i.Effort,
		&i.PermissionMode,
		&i.PromptVersion,
		&i.Cwd,
		&i.Pid,
		&i.CostUsd,
		&i.CostTotalUsd,
		&i.InputTokens,
		&i.OutputTokens,
		&i.Turns,
		&i.Denials,
		&i.Result,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const dailyCost = `-- name: DailyCost :many
SELECT CAST(date(created_at) AS TEXT) AS day, CAST(SUM(cost_usd) AS REAL) AS cost, COUNT(*) AS runs
FROM runs WHERE created_at >= ?1
GROUP BY date(created_at) ORDER BY day
`

type DailyCostRow struct {
	Day  string  `json:"day"`
	Cost float64 `json:"cost"`
	Runs int64   `json:"runs"`
}

func (q *Queries) DailyCost(ctx context.Context, since time.Time) ([]DailyCostRow, error) {
	rows, err := q.db.QueryContext(ctx, dailyCost, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyCostRow{}
	for rows.Next() {
		var i DailyCostRow
		if err := rows.Scan(&i.Day, &i.Cost, &i.Runs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishRun = `-- name: FinishRun :exec
UPDATE runs
SET status = ?1, reason = ?2, ended_at = ?3, session_id = ?4,
    cost_usd = ?5, cost_total_usd = ?6, input_tokens = ?7, output_tokens = ?8,
    turns = ?9, denials = ?10, result = ?11, pid = 0
WHERE id = ?12
`

type FinishRunParams struct {
	Status       string       `json:"status"`
	Reason       string       `json:"reason"`
	Now          sql.NullTime `json:"now"`
	SessionID    string       `json:"session_id"`
	CostUsd      float64      `json:"cost_usd"`
	CostTotalUsd float64      `json:"cost_total_usd"`
	InputTokens  int64        `json:"input_tokens"`
	OutputTokens int64        `json:"output_tokens"`
	Turns        int64        `json:"turns"`
	Denials      int64        `json:"denials"`
	Result       string       `json:"result"`
	ID           string       `json:"id"`
}

func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) error {
	_, err := q.db.ExecContext(ctx, finishRun,
		arg.Status,
		arg.Reason,
		arg.Now,
		arg.SessionID,
		arg.CostUsd,
		arg.CostTotalUsd,
		arg.InputTokens,
		arg.OutputTokens,
		arg.Turns,
		arg.Denials,
		arg.Result,
		arg.ID,
	)
	return err
}

const getRun = `-- name: GetRun :one
SELECT id, unit_id, project_id, parent_run_id, kind, status, reason, session_id, model, effort, permission_mode, prompt_version, cwd, pid, cost_usd, cost_total_usd, input_tokens, output_tokens, turns, denials, result, created_at, started_at, ended_at FROM runs WHERE id = ?1
`

func (q *Queries) GetRun(ctx context.Context, id string) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.ProjectID,
		&i.ParentRunID,
		&i.Kind,
		&i.Status,
		&i.Reason,
		&i.SessionID,
		&i.Model,
		&i.Effort,
		&i.PermissionMode,
		&i.PromptVersion,
		&i.Cwd,
		&i.Pid,
		&i.CostUsd,
		&i.CostTotalUsd,
		&i.InputTokens,
		&i.OutputTokens,
		&i.Turns,
		&i.Denials,
		&i.Result,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const interruptRun = `-- name: InterruptRun :exec
UPDATE runs SET status = 'interrupted', reason = ?1, ended_at = ?2, pid = 0 WHERE id = ?3
`

type InterruptRunParams struct {
	Reason string       `json:"reason"`
	Now    sql.NullTime `json:"now"`
	ID     string       `json:"id"`
}

func (q *Queries) InterruptRun(ctx context.Context, arg InterruptRunParams) error {
	_, err := q.db.ExecContext(ctx, interruptRun, arg.Reason, arg.Now, arg.ID)
	return err
}

const lastSessionRun = `-- name: LastSessionRun :one
SELECT id, unit_id, project_id, parent_run_id, kind, status, reason, session_id, model, effort, permission_mode, prompt_version, cwd, pid, cost_usd, cost_total_usd, input_tokens, output_tokens, turns, denials, result, created_at, started_at, ended_at FROM runs
WHERE unit_id = ?1 AND kind = ?2 AND session_id != '' AND status IN ('succeeded', 'failed', 'cancelled', 'timed_out', 'budget_exceeded', 'interrupted')
ORDER BY created_at DESC LIMIT 1
`

type LastSessionRunParams struct {
	UnitID sql.NullString `json:"unit_id"`
	Kind   string         `json:"kind"`
}

// The most recent run of a kind that left a resumable session.
func (q *Queries) LastSessionRun(ctx context.Context, arg LastSessionRunParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, lastSessionRun, arg.UnitID, arg.Kind)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.ProjectID,
		&i.ParentRunID,
		&i.Kind,
		&i.Status,
		&i.Reason,
		&i.SessionID,
		&i.Model,
		&i.Effort,
		&i.PermissionMode,
		&i.PromptVersion,
		&i.Cwd,
		&i.Pid,
		&i.CostUsd,
		&i.CostTotalUsd,
		&i.InputTokens,
		&i.OutputTokens,
		&i.Turns,
		&i.Denials,
		&i.Result,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const listLiveRuns = `-- name: ListLiveRuns :many
SELECT id, unit_id, project_id, parent_run_id, kind, status, reason, session_id, model, effort, permission_mode, prompt_version, cwd, pid, cost_usd, cost_total_usd, input_tokens, output_tokens, turns, denials, result, created_at, started_at, ended_at FROM runs WHERE status IN ('queued', 'running')
`

func (q *Queries) ListLiveRuns(ctx context.Context) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listLiveRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.ProjectID,
			&i.ParentRunID,
			&i.Kind,
			&i.Status,
			&i.Reason,
			&i.SessionID,
			&i.Model,
			&i.Effort,
			&i.PermissionMode,
			&i.PromptVersion,
			&i.Cwd,
			&i.Pid,
			&i.CostUsd,
			&i.CostTotalUsd,
			&i.InputTokens,
			&i.OutputTokens,
			&i.Turns,
			&i.Denials,
			&i.Result,
			&i.CreatedAt,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT runs.id, runs.unit_id, runs.project_id, runs.parent_run_id, runs.kind, runs.status, runs.reason, runs.session_id, runs.model, runs.effort, runs.permission_mode, runs.prompt_version, runs.cwd, runs.pid, runs.cost_usd, runs.cost_total_usd, runs.input_tokens, runs.output_tokens, runs.turns, runs.denials, runs.result, runs.created_at, runs.started_at, runs.ended_at, COALESCE(units.seq, 0) AS unit_seq, COALESCE(units.title, '') AS unit_title
FROM runs LEFT JOIN units ON units.id = runs.unit_id
WHERE (?1 IS NULL OR runs.unit_id = ?1)
  AND (?2 IS NULL OR runs.project_id = ?2)
ORDER BY runs.created_at DESC
LIMIT ?3
`

type ListRunsParams struct {
	UnitID    interface{} `json:"unit_id"`
	ProjectID interface{} `json:"project_id"`
	Lim       int64       `json:"lim"`
}

type ListRunsRow struct {
	ID             string         `json:"id"`
	UnitID         sql.NullString `json:"unit_id"`
	ProjectID      sql.NullString `json:"project_id"`
	ParentRunID    string         `json:"parent_run_id"`
	Kind           string         `json:"kind"`
	Status         string         `json:"status"`
	Reason         string         `json:"reason"`
	SessionID      string         `json:"session_id"`
	Model          string         `json:"model"`
	Effort         string         `json:"effort"`
	PermissionMode string         `json:"permission_mode"`
	PromptVersion  string         `json:"prompt_version"`
	Cwd            string         `json:"cwd"`
	Pid            int64          `json:"pid"`
	CostUsd        float64        `json:"cost_usd"`
	CostTotalUsd   float64        `json:"cost_total_usd"`
	InputTokens    int64          `json:"input_tokens"`
	OutputTokens   int64          `json:"output_tokens"`
	Turns          int64          `json:"turns"`
	Denials        int64          `json:"denials"`
	Result         string         `json:"result"`
	CreatedAt      time.Time      `json:"created_at"`
	StartedAt      sql.NullTime   `json:"started_at"`
	EndedAt        sql.NullTime   `json:"ended_at"`
	UnitSeq        int64          `json:"unit_seq"`
	UnitTitle      string         `json:"unit_title"`
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]ListRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRuns, arg.UnitID, arg.ProjectID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsRow{}
	for rows.Next() {
		var i ListRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.ProjectID,
			&i.ParentRunID,
			&i.Kind,
			&i.Status,
			&i.Reason,
			&i.SessionID,
			&i.Model,
			&i.Effort,
			&i.PermissionMode,
			&i.PromptVersion,
			&i.Cwd,
			&i.Pid,
			&i.CostUsd,
			&i.CostTotalUsd,
			&i.InputTokens,
			&i.OutputTokens,
			&i.Turns,
			&i.Denials,
			&i.Result,
			&i.CreatedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.UnitSeq,
			&i.UnitTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRunSession = `-- name: SetRunSession :exec
UPDATE runs SET session_id = ?1 WHERE id = ?2
`

type SetRunSessionParams struct {
	SessionID string `json:"session_id"`
	ID        string `json:"id"`
}

func (q *Queries) SetRunSession(ctx context.Context, arg SetRunSessionParams) error {
	_, err := q.db.ExecContext(ctx, setRunSession, arg.SessionID, arg.ID)
	return err
}

const startRun = `-- name: StartRun :exec
UPDATE runs SET status = 'running', pid = ?1, started_at = ?2 WHERE id = ?3
`

type StartRunParams struct {
	Pid int64        `json:"pid"`
	Now sql.NullTime `json:"now"`
	ID  string       `json:"id"`
}

func (q *Queries) StartRun(ctx context.Context, arg StartRunParams) error {
	_, err := q.db.ExecContext(ctx, startRun, arg.Pid, arg.Now, arg.ID)
	return err
}

const sumCost = `-- name: SumCost :one
SELECT CAST(COALESCE(SUM(cost_usd), 0) AS REAL) AS total FROM runs WHERE created_at >= ?1
`

func (q *Queries) SumCost(ctx context.Context, since time.Time) (float64, error) {
	row := q.db.QueryRowContext(ctx, sumCost, since)
	var total float64
	err := row.Scan(&total)
	return total, err
}
