// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: slack.sql

package db

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const countFeedbackByStatus = `-- name: CountFeedbackByStatus :many
SELECT triage_status, COUNT(*) AS n FROM feedback
WHERE (?1 IS NULL OR project_id = ?1)
GROUP BY triage_status
`

type CountFeedbackByStatusRow struct {
	TriageStatus string `json:"triage_status"`
	N            int64  `json:"n"`
}

func (q *Queries) CountFeedbackByStatus(ctx context.Context, projectID interface{}) ([]CountFeedbackByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countFeedbackByStatus, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountFeedbackByStatusRow{}
	for rows.Next() {
		var i CountFeedbackByStatusRow
		if err := rows.Scan(&i.TriageStatus, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSlackSource = `-- name: CreateSlackSource :one
INSERT INTO slack_sources (id, project_id, channel_id, channel_name, auto_triage, exclude_bots, poll_interval_s, cursor_ts, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
RETURNING id, project_id, channel_id, channel_name, auto_triage, exclude_bots, poll_interval_s, cursor_ts, last_polled_at, last_thread_sweep_at, last_error, created_at
`

type CreateSlackSourceParams struct {
	ID            string    `json:"id"`
	ProjectID     string    `json:"project_id"`
	ChannelID     string    `json:"channel_id"`
	ChannelName   string    `json:"channel_name"`
	AutoTriage    bool      `json:"auto_triage"`
	ExcludeBots   bool      `json:"exclude_bots"`
	PollIntervalS int64     `json:"poll_interval_s"`
	CursorTs      string    `json:"cursor_ts"`
	Now           time.Time `json:"now"`
}

func (q *Queries) CreateSlackSource(ctx context.Context, arg CreateSlackSourceParams) (SlackSource, error) {
	row := q.db.QueryRowContext(ctx, createSlackSource,
		arg.ID,
		arg.ProjectID,
		arg.ChannelID,
		arg.ChannelName,
		arg.AutoTriage,
		arg.ExcludeBots,
		arg.PollIntervalS,
		arg.CursorTs,
		arg.Now,
	)
	var i SlackSource
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ChannelID,
		&i.ChannelName,
		&i.AutoTriage,
		&i.ExcludeBots,
		&i.PollIntervalS,
		&i.CursorTs,
		&i.LastPolledAt,
		&i.LastThreadSweepAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSlackSource = `-- name: DeleteSlackSource :exec
DELETE FROM slack_sources WHERE id = ?1
`

func (q *Queries) DeleteSlackSource(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSlackSource, id)
	return err
}

const getFeedback = `-- name: GetFeedback :one
SELECT id, project_id, source_id, channel_id, channel_name, ts, thread_ts, author_id, author_name, text, permalink, reply_count, edited, posted_at, triage_status, triage, unit_id, created_at, updated_at FROM feedback WHERE id = ?1
`

func (q *Queries) GetFeedback(ctx context.Context, id string) (Feedback, error) {
	row := q.db.QueryRowContext(ctx, getFeedback, id)
	var i Feedback
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceID,
		&i.ChannelID,
		&i.ChannelName,
		&i.Ts,
		&i.ThreadTs,
		&i.AuthorID,
		&i.AuthorName,
		&i.Text,
		&i.Permalink,
		&i.ReplyCount,
		&i.Edited,
		&i.PostedAt,
		&i.TriageStatus,
		&i.Triage,
		&i.UnitID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeedbackByTS = `-- name: GetFeedbackByTS :one
SELECT id, project_id, source_id, channel_id, channel_name, ts, thread_ts, author_id, author_name, text, permalink, reply_count, edited, posted_at, triage_status, triage, unit_id, created_at, updated_at FROM feedback WHERE channel_id = ?1 AND ts = ?2
`

type GetFeedbackByTSParams struct {
	ChannelID string `json:"channel_id"`
	Ts        string `json:"ts"`
}

func (q *Queries) GetFeedbackByTS(ctx context.Context, arg GetFeedbackByTSParams) (Feedback, error) {
	row := q.db.QueryRowContext(ctx, getFeedbackByTS, arg.ChannelID, arg.Ts)
	var i Feedback
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceID,
		&i.ChannelID,
		&i.ChannelName,
		&i.Ts,
		&i.ThreadTs,
		&i.AuthorID,
		&i.AuthorName,
		&i.Text,
		&i.Permalink,
		&i.ReplyCount,
		&i.Edited,
		&i.PostedAt,
		&i.TriageStatus,
		&i.Triage,
		&i.UnitID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSlackSource = `-- name: GetSlackSource :one
SELECT id, project_id, channel_id, channel_name, auto_triage, exclude_bots, poll_interval_s, cursor_ts, last_polled_at, last_thread_sweep_at, last_error, created_at FROM slack_sources WHERE id = ?1
`

func (q *Queries) GetSlackSource(ctx context.Context, id string) (SlackSource, error) {
	row := q.db.QueryRowContext(ctx, getSlackSource, id)
	var i SlackSource
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ChannelID,
		&i.ChannelName,
		&i.AutoTriage,
		&i.ExcludeBots,
		&i.PollIntervalS,
		&i.CursorTs,
		&i.LastPolledAt,
		&i.LastThreadSweepAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const linkFeedback = `-- name: LinkFeedback :exec
UPDATE feedback SET unit_id = ?1, triage_status = ?2, updated_at = ?3 WHERE id IN (/*SLICE:ids*/?)
`

type LinkFeedbackParams struct {
	UnitID       sql.NullString `json:"unit_id"`
	TriageStatus string         `json:"triage_status"`
	Now          time.Time      `json:"now"`
	Ids          []string       `json:"ids"`
}

func (q *Queries) LinkFeedback(ctx context.Context, arg LinkFeedbackParams) error {
	query := linkFeedback
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UnitID)
	queryParams = append(queryParams, arg.TriageStatus)
	queryParams = append(queryParams, arg.Now)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const listFeedback = `-- name: ListFeedback :many
SELECT feedback.id, feedback.project_id, feedback.source_id, feedback.channel_id, feedback.channel_name, feedback.ts, feedback.thread_ts, feedback.author_id, feedback.author_name, feedback.text, feedback.permalink, feedback.reply_count, feedback.edited, feedback.posted_at, feedback.triage_status, feedback.triage, feedback.unit_id, feedback.created_at, feedback.updated_at, COALESCE(units.seq, 0) AS unit_seq, COALESCE(units.title, '') AS unit_title, COALESCE(units.state, '') AS unit_state
FROM feedback LEFT JOIN units ON units.id = feedback.unit_id
WHERE (?1 IS NULL OR feedback.project_id = ?1)
ORDER BY feedback.posted_at DESC
LIMIT ?2
`

type ListFeedbackParams struct {
	ProjectID interface{} `json:"project_id"`
	Lim       int64       `json:"lim"`
}

type ListFeedbackRow struct {
	ID           string         `json:"id"`
	ProjectID    string         `json:"project_id"`
	SourceID     sql.NullString `json:"source_id"`
	ChannelID    string         `json:"channel_id"`
	ChannelName  string         `json:"channel_name"`
	Ts           string         `json:"ts"`
	ThreadTs     string         `json:"thread_ts"`
	AuthorID     string         `json:"author_id"`
	AuthorName   string         `json:"author_name"`
	Text         string         `json:"text"`
	Permalink    string         `json:"permalink"`
	ReplyCount   int64          `json:"reply_count"`
	Edited       bool           `json:"edited"`
	PostedAt     time.Time      `json:"posted_at"`
	TriageStatus string         `json:"triage_status"`
	Triage       string         `json:"triage"`
	UnitID       sql.NullString `json:"unit_id"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	UnitSeq      int64          `json:"unit_seq"`
	UnitTitle    string         `json:"unit_title"`
	UnitState    string         `json:"unit_state"`
}

func (q *Queries) ListFeedback(ctx context.Context, arg ListFeedbackParams) ([]ListFeedbackRow, error) {
	rows, err := q.db.QueryContext(ctx, listFeedback, arg.ProjectID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeedbackRow{}
	for rows.Next() {
		var i ListFeedbackRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceID,
			&i.ChannelID,
			&i.ChannelName,
			&i.Ts,
			&i.ThreadTs,
			&i.AuthorID,
			&i.AuthorName,
			&i.Text,
			&i.Permalink,
			&i.ReplyCount,
			&i.Edited,
			&i.PostedAt,
			&i.TriageStatus,
			&i.Triage,
			&i.UnitID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UnitSeq,
			&i.UnitTitle,
			&i.UnitState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedbackByIDs = `-- name: ListFeedbackByIDs :many
SELECT id, project_id, source_id, channel_id, channel_name, ts, thread_ts, author_id, author_name, text, permalink, reply_count, edited, posted_at, triage_status, triage, unit_id, created_at, updated_at FROM feedback WHERE id IN (/*SLICE:ids*/?) ORDER BY posted_at
`

func (q *Queries) ListFeedbackByIDs(ctx context.Context, ids []string) ([]Feedback, error) {
	query := listFeedbackByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feedback{}
	for rows.Next() {
		var i Feedback
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceID,
			&i.ChannelID,
			&i.ChannelName,
			&i.Ts,
			&i.ThreadTs,
			&i.AuthorID,
			&i.AuthorName,
			&i.Text,
			&i.Permalink,
			&i.ReplyCount,
			&i.Edited,
			&i.PostedAt,
			&i.TriageStatus,
			&i.Triage,
			&i.UnitID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedbackByUnit = `-- name: ListFeedbackByUnit :many
SELECT id, project_id, source_id, channel_id, channel_name, ts, thread_ts, author_id, author_name, text, permalink, reply_count, edited, posted_at, triage_status, triage, unit_id, created_at, updated_at FROM feedback WHERE unit_id = ?1 ORDER BY posted_at
`

func (q *Queries) ListFeedbackByUnit(ctx context.Context, unitID sql.NullString) ([]Feedback, error) {
	rows, err := q.db.QueryContext(ctx, listFeedbackByUnit, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feedback{}
	for rows.Next() {
		var i Feedback
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceID,
			&i.ChannelID,
			&i.ChannelName,
			&i.Ts,
			&i.ThreadTs,
			&i.AuthorID,
			&i.AuthorName,
			&i.Text,
			&i.Permalink,
			&i.ReplyCount,
			&i.Edited,
			&i.PostedAt,
			&i.TriageStatus,
			&i.Triage,
			&i.UnitID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewFeedback = `-- name: ListNewFeedback :many
SELECT id, project_id, source_id, channel_id, channel_name, ts, thread_ts, author_id, author_name, text, permalink, reply_count, edited, posted_at, triage_status, triage, unit_id, created_at, updated_at FROM feedback WHERE project_id = ?1 AND triage_status = 'new' ORDER BY posted_at LIMIT ?2
`

type ListNewFeedbackParams struct {
	ProjectID string `json:"project_id"`
	Lim       int64  `json:"lim"`
}

func (q *Queries) ListNewFeedback(ctx context.Context, arg ListNewFeedbackParams) ([]Feedback, error) {
	rows, err := q.db.QueryContext(ctx, listNewFeedback, arg.ProjectID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feedback{}
	for rows.Next() {
		var i Feedback
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceID,
			&i.ChannelID,
			&i.ChannelName,
			&i.Ts,
			&i.ThreadTs,
			&i.AuthorID,
			&i.AuthorName,
			&i.Text,
			&i.Permalink,
			&i.ReplyCount,
			&i.Edited,
			&i.PostedAt,
			&i.TriageStatus,
			&i.Triage,
			&i.UnitID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsWithNewFeedback = `-- name: ListProjectsWithNewFeedback :many
SELECT DISTINCT project_id FROM feedback WHERE triage_status = 'new'
`

func (q *Queries) ListProjectsWithNewFeedback(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsWithNewFeedback)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var project_id string
		if err := rows.Scan(&project_id); err != nil {
			return nil, err
		}
		items = append(items, project_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlackSources = `-- name: ListSlackSources :many
SELECT id, project_id, channel_id, channel_name, auto_triage, exclude_bots, poll_interval_s, cursor_ts, last_polled_at, last_thread_sweep_at, last_error, created_at FROM slack_sources ORDER BY channel_name
`

func (q *Queries) ListSlackSources(ctx context.Context) ([]SlackSource, error) {
	rows, err := q.db.QueryContext(ctx, listSlackSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SlackSource{}
	for rows.Next() {
		var i SlackSource
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ChannelID,
			&i.ChannelName,
			&i.AutoTriage,
			&i.ExcludeBots,
			&i.PollIntervalS,
			&i.CursorTs,
			&i.LastPolledAt,
			&i.LastThreadSweepAt,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlackSourcesByProject = `-- name: ListSlackSourcesByProject :many
SELECT id, project_id, channel_id, channel_name, auto_triage, exclude_bots, poll_interval_s, cursor_ts, last_polled_at, last_thread_sweep_at, last_error, created_at FROM slack_sources WHERE project_id = ?1 ORDER BY channel_name
`

func (q *Queries) ListSlackSourcesByProject(ctx context.Context, projectID string) ([]SlackSource, error) {
	rows, err := q.db.QueryContext(ctx, listSlackSourcesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SlackSource{}
	for rows.Next() {
		var i SlackSource
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ChannelID,
			&i.ChannelName,
			&i.AutoTriage,
			&i.ExcludeBots,
			&i.PollIntervalS,
			&i.CursorTs,
			&i.LastPolledAt,
			&i.LastThreadSweepAt,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadReplies = `-- name: ListThreadReplies :many
SELECT id, project_id, source_id, channel_id, channel_name, ts, thread_ts, author_id, author_name, text, permalink, reply_count, edited, posted_at, triage_status, triage, unit_id, created_at, updated_at FROM feedback WHERE channel_id = ?1 AND thread_ts = ?2 AND ts != ?2 ORDER BY posted_at
`

type ListThreadRepliesParams struct {
	ChannelID string `json:"channel_id"`
	ThreadTs  string `json:"thread_ts"`
}

func (q *Queries) ListThreadReplies(ctx context.Context, arg ListThreadRepliesParams) ([]Feedback, error) {
	rows, err := q.db.QueryContext(ctx, listThreadReplies, arg.ChannelID, arg.ThreadTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feedback{}
	for rows.Next() {
		var i Feedback
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceID,
			&i.ChannelID,
			&i.ChannelName,
			&i.Ts,
			&i.ThreadTs,
			&i.AuthorID,
			&i.AuthorName,
			&i.Text,
			&i.Permalink,
			&i.ReplyCount,
			&i.Edited,
			&i.PostedAt,
			&i.TriageStatus,
			&i.Triage,
			&i.UnitID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetTriagingFeedback = `-- name: ResetTriagingFeedback :exec
UPDATE feedback SET triage_status = 'new' WHERE triage_status = 'triaging'
`

func (q *Queries) ResetTriagingFeedback(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetTriagingFeedback)
	return err
}

const setFeedbackStatus = `-- name: SetFeedbackStatus :exec
UPDATE feedback SET triage_status = ?1, updated_at = ?2 WHERE id IN (/*SLICE:ids*/?)
`

type SetFeedbackStatusParams struct {
	TriageStatus string    `json:"triage_status"`
	Now          time.Time `json:"now"`
	Ids          []string  `json:"ids"`
}

func (q *Queries) SetFeedbackStatus(ctx context.Context, arg SetFeedbackStatusParams) error {
	query := setFeedbackStatus
	var queryParams []interface{}
	queryParams = append(queryParams, arg.TriageStatus)
	queryParams = append(queryParams, arg.Now)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const setFeedbackTriage = `-- name: SetFeedbackTriage :exec
UPDATE feedback SET triage_status = ?1, triage = ?2, unit_id = ?3, updated_at = ?4 WHERE id = ?5
`

type SetFeedbackTriageParams struct {
	TriageStatus string         `json:"triage_status"`
	Triage       string         `json:"triage"`
	UnitID       sql.NullString `json:"unit_id"`
	Now          time.Time      `json:"now"`
	ID           string         `json:"id"`
}

func (q *Queries) SetFeedbackTriage(ctx context.Context, arg SetFeedbackTriageParams) error {
	_, err := q.db.ExecContext(ctx, setFeedbackTriage,
		arg.TriageStatus,
		arg.Triage,
		arg.UnitID,
		arg.Now,
		arg.ID,
	)
	return err
}

const setSlackSourcePolled = `-- name: SetSlackSourcePolled :exec
UPDATE slack_sources SET cursor_ts = ?1, last_polled_at = ?2, last_error = ?3 WHERE id = ?4
`

type SetSlackSourcePolledParams struct {
	CursorTs  string       `json:"cursor_ts"`
	Now       sql.NullTime `json:"now"`
	LastError string       `json:"last_error"`
	ID        string       `json:"id"`
}

func (q *Queries) SetSlackSourcePolled(ctx context.Context, arg SetSlackSourcePolledParams) error {
	_, err := q.db.ExecContext(ctx, setSlackSourcePolled,
		arg.CursorTs,
		arg.Now,
		arg.LastError,
		arg.ID,
	)
	return err
}

const setSlackSourceSwept = `-- name: SetSlackSourceSwept :exec
UPDATE slack_sources SET last_thread_sweep_at = ?1 WHERE id = ?2
`

type SetSlackSourceSweptParams struct {
	Now sql.NullTime `json:"now"`
	ID  string       `json:"id"`
}

func (q *Queries) SetSlackSourceSwept(ctx context.Context, arg SetSlackSourceSweptParams) error {
	_, err := q.db.ExecContext(ctx, setSlackSourceSwept, arg.Now, arg.ID)
	return err
}

const unlinkFeedbackFromUnit = `-- name: UnlinkFeedbackFromUnit :exec
UPDATE feedback SET unit_id = NULL, triage_status = 'inbox', updated_at = ?1 WHERE unit_id = ?2
`

type UnlinkFeedbackFromUnitParams struct {
	Now    time.Time      `json:"now"`
	UnitID sql.NullString `json:"unit_id"`
}

func (q *Queries) UnlinkFeedbackFromUnit(ctx context.Context, arg UnlinkFeedbackFromUnitParams) error {
	_, err := q.db.ExecContext(ctx, unlinkFeedbackFromUnit, arg.Now, arg.UnitID)
	return err
}

const updateSlackSource = `-- name: UpdateSlackSource :one
UPDATE slack_sources SET auto_triage = ?1, exclude_bots = ?2, poll_interval_s = ?3
WHERE id = ?4
RETURNING id, project_id, channel_id, channel_name, auto_triage, exclude_bots, poll_interval_s, cursor_ts, last_polled_at, last_thread_sweep_at, last_error, created_at
`

type UpdateSlackSourceParams struct {
	AutoTriage    bool   `json:"auto_triage"`
	ExcludeBots   bool   `json:"exclude_bots"`
	PollIntervalS int64  `json:"poll_interval_s"`
	ID            string `json:"id"`
}

func (q *Queries) UpdateSlackSource(ctx context.Context, arg UpdateSlackSourceParams) (SlackSource, error) {
	row := q.db.QueryRowContext(ctx, updateSlackSource,
		arg.AutoTriage,
		arg.ExcludeBots,
		arg.PollIntervalS,
		arg.ID,
	)
	var i SlackSource
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ChannelID,
		&i.ChannelName,
		&i.AutoTriage,
		&i.ExcludeBots,
		&i.PollIntervalS,
		&i.CursorTs,
		&i.LastPolledAt,
		&i.LastThreadSweepAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const upsertFeedback = `-- name: UpsertFeedback :one
INSERT INTO feedback (id, project_id, source_id, channel_id, channel_name, ts, thread_ts, author_id, author_name, text,
                      permalink, reply_count, edited, posted_at, triage_status, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10,
        ?11, ?12, ?13, ?14, ?15, ?16, ?16)
ON CONFLICT (channel_id, ts) DO UPDATE SET
    text = excluded.text,
    edited = excluded.edited,
    reply_count = MAX(feedback.reply_count, excluded.reply_count),
    author_name = CASE WHEN excluded.author_name != '' THEN excluded.author_name ELSE feedback.author_name END,
    permalink = CASE WHEN excluded.permalink != '' THEN excluded.permalink ELSE feedback.permalink END,
    updated_at = excluded.updated_at
RETURNING id, project_id, source_id, channel_id, channel_name, ts, thread_ts, author_id, author_name, text, permalink, reply_count, edited, posted_at, triage_status, triage, unit_id, created_at, updated_at
`

type UpsertFeedbackParams struct {
	ID           string         `json:"id"`
	ProjectID    string         `json:"project_id"`
	SourceID     sql.NullString `json:"source_id"`
	ChannelID    string         `json:"channel_id"`
	ChannelName  string         `json:"channel_name"`
	Ts           string         `json:"ts"`
	ThreadTs     string         `json:"thread_ts"`
	AuthorID     string         `json:"author_id"`
	AuthorName   string         `json:"author_name"`
	Text         string         `json:"text"`
	Permalink    string         `json:"permalink"`
	ReplyCount   int64          `json:"reply_count"`
	Edited       bool           `json:"edited"`
	PostedAt     time.Time      `json:"posted_at"`
	TriageStatus string         `json:"triage_status"`
	Now          time.Time      `json:"now"`
}

// Re-reading a message updates what can change (text, reply count) and
// never its triage.
func (q *Queries) UpsertFeedback(ctx context.Context, arg UpsertFeedbackParams) (Feedback, error) {
	row := q.db.QueryRowContext(ctx, upsertFeedback,
		arg.ID,
		arg.ProjectID,
		arg.SourceID,
		arg.ChannelID,
		arg.ChannelName,
		arg.Ts,
		arg.ThreadTs,
		arg.AuthorID,
		arg.AuthorName,
		arg.Text,
		arg.Permalink,
		arg.ReplyCount,
		arg.Edited,
		arg.PostedAt,
		arg.TriageStatus,
		arg.Now,
	)
	var i Feedback
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceID,
		&i.ChannelID,
		&i.ChannelName,
		&i.Ts,
		&i.ThreadTs,
		&i.AuthorID,
		&i.AuthorName,
		&i.Text,
		&i.Permalink,
		&i.ReplyCount,
		&i.Edited,
		&i.PostedAt,
		&i.TriageStatus,
		&i.Triage,
		&i.UnitID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
