// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: units.sql

package db

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const createUnit = `-- name: CreateUnit :one
INSERT INTO units (id, seq, project_id, parent_unit_id, kind, title, summary, description, origin, state,
                   workspace_path, created_by, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10,
        ?11, ?12, ?13, ?13)
RETURNING id, seq, project_id, parent_unit_id, kind, title, summary, description, origin, state, attention, attention_detail, review_iteration, workspace_path, created_by, created_at, updated_at
`

type CreateUnitParams struct {
	ID            string         `json:"id"`
	Seq           int64          `json:"seq"`
	ProjectID     string         `json:"project_id"`
	ParentUnitID  sql.NullString `json:"parent_unit_id"`
	Kind          string         `json:"kind"`
	Title         string         `json:"title"`
	Summary       string         `json:"summary"`
	Description   string         `json:"description"`
	Origin        string         `json:"origin"`
	State         string         `json:"state"`
	WorkspacePath string         `json:"workspace_path"`
	CreatedBy     string         `json:"created_by"`
	Now           time.Time      `json:"now"`
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (Unit, error) {
	row := q.db.QueryRowContext(ctx, createUnit,
		arg.ID,
		arg.Seq,
		arg.ProjectID,
		arg.ParentUnitID,
		arg.Kind,
		arg.Title,
		arg.Summary,
		arg.Description,
		arg.Origin,
		arg.State,
		arg.WorkspacePath,
		arg.CreatedBy,
		arg.Now,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.ProjectID,
		&i.ParentUnitID,
		&i.Kind,
		&i.Title,
		&i.Summary,
		&i.Description,
		&i.Origin,
		&i.State,
		&i.Attention,
		&i.AttentionDetail,
		&i.ReviewIteration,
		&i.WorkspacePath,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnit = `-- name: GetUnit :one
SELECT id, seq, project_id, parent_unit_id, kind, title, summary, description, origin, state, attention, attention_detail, review_iteration, workspace_path, created_by, created_at, updated_at FROM units WHERE id = ?1
`

func (q *Queries) GetUnit(ctx context.Context, id string) (Unit, error) {
	row := q.db.QueryRowContext(ctx, getUnit, id)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.ProjectID,
		&i.ParentUnitID,
		&i.Kind,
		&i.Title,
		&i.Summary,
		&i.Description,
		&i.Origin,
		&i.State,
		&i.Attention,
		&i.AttentionDetail,
		&i.ReviewIteration,
		&i.WorkspacePath,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUnits = `-- name: ListUnits :many
SELECT id, seq, project_id, parent_unit_id, kind, title, summary, description, origin, state, attention, attention_detail, review_iteration, workspace_path, created_by, created_at, updated_at FROM units
WHERE (?1 IS NULL OR project_id = ?1)
ORDER BY updated_at DESC
LIMIT ?2
`

type ListUnitsParams struct {
	ProjectID interface{} `json:"project_id"`
	Lim       int64       `json:"lim"`
}

func (q *Queries) ListUnits(ctx context.Context, arg ListUnitsParams) ([]Unit, error) {
	rows, err := q.db.QueryContext(ctx, listUnits, arg.ProjectID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Unit{}
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.ProjectID,
			&i.ParentUnitID,
			&i.Kind,
			&i.Title,
			&i.Summary,
			&i.Description,
			&i.Origin,
			&i.State,
			&i.Attention,
			&i.AttentionDetail,
			&i.ReviewIteration,
			&i.WorkspacePath,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitsInStates = `-- name: ListUnitsInStates :many
SELECT id, seq, project_id, parent_unit_id, kind, title, summary, description, origin, state, attention, attention_detail, review_iteration, workspace_path, created_by, created_at, updated_at FROM units WHERE state IN (/*SLICE:states*/?) ORDER BY updated_at
`

func (q *Queries) ListUnitsInStates(ctx context.Context, states []string) ([]Unit, error) {
	query := listUnitsInStates
	var queryParams []interface{}
	if len(states) > 0 {
		for _, v := range states {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:states*/?", strings.Repeat(",?", len(states))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:states*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Unit{}
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.ProjectID,
			&i.ParentUnitID,
			&i.Kind,
			&i.Title,
			&i.Summary,
			&i.Description,
			&i.Origin,
			&i.State,
			&i.Attention,
			&i.AttentionDetail,
			&i.ReviewIteration,
			&i.WorkspacePath,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextUnitSeq = `-- name: NextUnitSeq :one
SELECT CAST(COALESCE(MAX(seq), 0) + 1 AS INTEGER) AS next FROM units
`

func (q *Queries) NextUnitSeq(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextUnitSeq)
	var next int64
	err := row.Scan(&next)
	return next, err
}

const setUnitAttention = `-- name: SetUnitAttention :exec
UPDATE units SET attention = ?1, attention_detail = ?2, updated_at = ?3 WHERE id = ?4
`

type SetUnitAttentionParams struct {
	Attention       string    `json:"attention"`
	AttentionDetail string    `json:"attention_detail"`
	Now             time.Time `json:"now"`
	ID              string    `json:"id"`
}

func (q *Queries) SetUnitAttention(ctx context.Context, arg SetUnitAttentionParams) error {
	_, err := q.db.ExecContext(ctx, setUnitAttention,
		arg.Attention,
		arg.AttentionDetail,
		arg.Now,
		arg.ID,
	)
	return err
}

const setUnitReviewIteration = `-- name: SetUnitReviewIteration :exec
UPDATE units SET review_iteration = ?1, updated_at = ?2 WHERE id = ?3
`

type SetUnitReviewIterationParams struct {
	ReviewIteration int64     `json:"review_iteration"`
	Now             time.Time `json:"now"`
	ID              string    `json:"id"`
}

func (q *Queries) SetUnitReviewIteration(ctx context.Context, arg SetUnitReviewIterationParams) error {
	_, err := q.db.ExecContext(ctx, setUnitReviewIteration, arg.ReviewIteration, arg.Now, arg.ID)
	return err
}

const touchUnit = `-- name: TouchUnit :exec
UPDATE units SET updated_at = ?1 WHERE id = ?2
`

type TouchUnitParams struct {
	Now time.Time `json:"now"`
	ID  string    `json:"id"`
}

func (q *Queries) TouchUnit(ctx context.Context, arg TouchUnitParams) error {
	_, err := q.db.ExecContext(ctx, touchUnit, arg.Now, arg.ID)
	return err
}

const transitionUnit = `-- name: TransitionUnit :execrows
UPDATE units SET state = ?1, attention = '', attention_detail = '', updated_at = ?2
WHERE id = ?3 AND state = ?4
`

type TransitionUnitParams struct {
	ToState   string    `json:"to_state"`
	Now       time.Time `json:"now"`
	ID        string    `json:"id"`
	FromState string    `json:"from_state"`
}

// Conditional on the current state, so concurrent actions cannot both apply.
func (q *Queries) TransitionUnit(ctx context.Context, arg TransitionUnitParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, transitionUnit,
		arg.ToState,
		arg.Now,
		arg.ID,
		arg.FromState,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUnitDetails = `-- name: UpdateUnitDetails :exec
UPDATE units SET title = ?1, kind = ?2, summary = ?3, updated_at = ?4 WHERE id = ?5
`

type UpdateUnitDetailsParams struct {
	Title   string    `json:"title"`
	Kind    string    `json:"kind"`
	Summary string    `json:"summary"`
	Now     time.Time `json:"now"`
	ID      string    `json:"id"`
}

func (q *Queries) UpdateUnitDetails(ctx context.Context, arg UpdateUnitDetailsParams) error {
	_, err := q.db.ExecContext(ctx, updateUnitDetails,
		arg.Title,
		arg.Kind,
		arg.Summary,
		arg.Now,
		arg.ID,
	)
	return err
}
