// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: unit_repos.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const listUnitRepos = `-- name: ListUnitRepos :many
SELECT ur.unit_id, ur.repo_id, ur.checkout_path, ur.base_sha, ur.is_target, ur.branch, ur.head_sha, ur.reviewed_sha, ur.publish_state, ur.pr_number, ur.pr_url, ur.pr_state, ur.checks_state, ur.merge_sha, ur.merged_at, ur.updated_at, ur.release_state, ur.release_runs, r.full_name, r.default_branch, r.clone_url, r.clone_path
FROM unit_repos ur JOIN repos r ON r.id = ur.repo_id
WHERE ur.unit_id = ?1
ORDER BY r.full_name
`

type ListUnitReposRow struct {
	UnitID        string       `json:"unit_id"`
	RepoID        string       `json:"repo_id"`
	CheckoutPath  string       `json:"checkout_path"`
	BaseSha       string       `json:"base_sha"`
	IsTarget      bool         `json:"is_target"`
	Branch        string       `json:"branch"`
	HeadSha       string       `json:"head_sha"`
	ReviewedSha   string       `json:"reviewed_sha"`
	PublishState  string       `json:"publish_state"`
	PrNumber      int64        `json:"pr_number"`
	PrUrl         string       `json:"pr_url"`
	PrState       string       `json:"pr_state"`
	ChecksState   string       `json:"checks_state"`
	MergeSha      string       `json:"merge_sha"`
	MergedAt      sql.NullTime `json:"merged_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
	ReleaseState  string       `json:"release_state"`
	ReleaseRuns   string       `json:"release_runs"`
	FullName      string       `json:"full_name"`
	DefaultBranch string       `json:"default_branch"`
	CloneUrl      string       `json:"clone_url"`
	ClonePath     string       `json:"clone_path"`
}

func (q *Queries) ListUnitRepos(ctx context.Context, unitID string) ([]ListUnitReposRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnitRepos, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnitReposRow{}
	for rows.Next() {
		var i ListUnitReposRow
		if err := rows.Scan(
			&i.UnitID,
			&i.RepoID,
			&i.CheckoutPath,
			&i.BaseSha,
			&i.IsTarget,
			&i.Branch,
			&i.HeadSha,
			&i.ReviewedSha,
			&i.PublishState,
			&i.PrNumber,
			&i.PrUrl,
			&i.PrState,
			&i.ChecksState,
			&i.MergeSha,
			&i.MergedAt,
			&i.UpdatedAt,
			&i.ReleaseState,
			&i.ReleaseRuns,
			&i.FullName,
			&i.DefaultBranch,
			&i.CloneUrl,
			&i.ClonePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUnitRepoBranch = `-- name: SetUnitRepoBranch :exec
UPDATE unit_repos SET branch = ?1, updated_at = ?2 WHERE unit_id = ?3 AND repo_id = ?4
`

type SetUnitRepoBranchParams struct {
	Branch string    `json:"branch"`
	Now    time.Time `json:"now"`
	UnitID string    `json:"unit_id"`
	RepoID string    `json:"repo_id"`
}

func (q *Queries) SetUnitRepoBranch(ctx context.Context, arg SetUnitRepoBranchParams) error {
	_, err := q.db.ExecContext(ctx, setUnitRepoBranch,
		arg.Branch,
		arg.Now,
		arg.UnitID,
		arg.RepoID,
	)
	return err
}

const setUnitRepoPRStatus = `-- name: SetUnitRepoPRStatus :exec
UPDATE unit_repos
SET pr_state = ?1, checks_state = ?2, head_sha = ?3, merge_sha = ?4, merged_at = ?5, updated_at = ?6
WHERE unit_id = ?7 AND repo_id = ?8
`

type SetUnitRepoPRStatusParams struct {
	PrState     string       `json:"pr_state"`
	ChecksState string       `json:"checks_state"`
	HeadSha     string       `json:"head_sha"`
	MergeSha    string       `json:"merge_sha"`
	MergedAt    sql.NullTime `json:"merged_at"`
	Now         time.Time    `json:"now"`
	UnitID      string       `json:"unit_id"`
	RepoID      string       `json:"repo_id"`
}

func (q *Queries) SetUnitRepoPRStatus(ctx context.Context, arg SetUnitRepoPRStatusParams) error {
	_, err := q.db.ExecContext(ctx, setUnitRepoPRStatus,
		arg.PrState,
		arg.ChecksState,
		arg.HeadSha,
		arg.MergeSha,
		arg.MergedAt,
		arg.Now,
		arg.UnitID,
		arg.RepoID,
	)
	return err
}

const setUnitRepoPublish = `-- name: SetUnitRepoPublish :exec
UPDATE unit_repos
SET publish_state = ?1, head_sha = ?2, pr_number = ?3, pr_url = ?4, pr_state = ?5, updated_at = ?6
WHERE unit_id = ?7 AND repo_id = ?8
`

type SetUnitRepoPublishParams struct {
	PublishState string    `json:"publish_state"`
	HeadSha      string    `json:"head_sha"`
	PrNumber     int64     `json:"pr_number"`
	PrUrl        string    `json:"pr_url"`
	PrState      string    `json:"pr_state"`
	Now          time.Time `json:"now"`
	UnitID       string    `json:"unit_id"`
	RepoID       string    `json:"repo_id"`
}

func (q *Queries) SetUnitRepoPublish(ctx context.Context, arg SetUnitRepoPublishParams) error {
	_, err := q.db.ExecContext(ctx, setUnitRepoPublish,
		arg.PublishState,
		arg.HeadSha,
		arg.PrNumber,
		arg.PrUrl,
		arg.PrState,
		arg.Now,
		arg.UnitID,
		arg.RepoID,
	)
	return err
}

const setUnitRepoRelease = `-- name: SetUnitRepoRelease :exec
UPDATE unit_repos SET release_state = ?1, release_runs = ?2, updated_at = ?3
WHERE unit_id = ?4 AND repo_id = ?5
`

type SetUnitRepoReleaseParams struct {
	ReleaseState string    `json:"release_state"`
	ReleaseRuns  string    `json:"release_runs"`
	Now          time.Time `json:"now"`
	UnitID       string    `json:"unit_id"`
	RepoID       string    `json:"repo_id"`
}

func (q *Queries) SetUnitRepoRelease(ctx context.Context, arg SetUnitRepoReleaseParams) error {
	_, err := q.db.ExecContext(ctx, setUnitRepoRelease,
		arg.ReleaseState,
		arg.ReleaseRuns,
		arg.Now,
		arg.UnitID,
		arg.RepoID,
	)
	return err
}

const setUnitRepoReviewed = `-- name: SetUnitRepoReviewed :exec
UPDATE unit_repos SET reviewed_sha = ?1, updated_at = ?2 WHERE unit_id = ?3 AND repo_id = ?4
`

type SetUnitRepoReviewedParams struct {
	ReviewedSha string    `json:"reviewed_sha"`
	Now         time.Time `json:"now"`
	UnitID      string    `json:"unit_id"`
	RepoID      string    `json:"repo_id"`
}

func (q *Queries) SetUnitRepoReviewed(ctx context.Context, arg SetUnitRepoReviewedParams) error {
	_, err := q.db.ExecContext(ctx, setUnitRepoReviewed,
		arg.ReviewedSha,
		arg.Now,
		arg.UnitID,
		arg.RepoID,
	)
	return err
}

const setUnitRepoTarget = `-- name: SetUnitRepoTarget :exec
UPDATE unit_repos SET is_target = ?1, updated_at = ?2 WHERE unit_id = ?3 AND repo_id = ?4
`

type SetUnitRepoTargetParams struct {
	IsTarget bool      `json:"is_target"`
	Now      time.Time `json:"now"`
	UnitID   string    `json:"unit_id"`
	RepoID   string    `json:"repo_id"`
}

func (q *Queries) SetUnitRepoTarget(ctx context.Context, arg SetUnitRepoTargetParams) error {
	_, err := q.db.ExecContext(ctx, setUnitRepoTarget,
		arg.IsTarget,
		arg.Now,
		arg.UnitID,
		arg.RepoID,
	)
	return err
}

const upsertUnitRepo = `-- name: UpsertUnitRepo :exec
INSERT INTO unit_repos (unit_id, repo_id, checkout_path, base_sha, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT (unit_id, repo_id) DO UPDATE SET checkout_path = excluded.checkout_path, base_sha = excluded.base_sha, updated_at = excluded.updated_at
`

type UpsertUnitRepoParams struct {
	UnitID       string    `json:"unit_id"`
	RepoID       string    `json:"repo_id"`
	CheckoutPath string    `json:"checkout_path"`
	BaseSha      string    `json:"base_sha"`
	Now          time.Time `json:"now"`
}

func (q *Queries) UpsertUnitRepo(ctx context.Context, arg UpsertUnitRepoParams) error {
	_, err := q.db.ExecContext(ctx, upsertUnitRepo,
		arg.UnitID,
		arg.RepoID,
		arg.CheckoutPath,
		arg.BaseSha,
		arg.Now,
	)
	return err
}
